# GoReleaser configuration for RagCode MCP Server
# See https://goreleaser.com for documentation

version: 2

project_name: rag-code-mcp

before:
  hooks:
    # Ensure dependencies are up to date
    - go mod tidy
    - go mod download

builds:
  - id: rag-code-mcp
    main: ./cmd/rag-code-mcp
    binary: rag-code-mcp
    
    env:
      - CGO_ENABLED=0
    
    goos:
      - linux
      - darwin
      - windows
    
    goarch:
      - amd64
      - arm64
    
    # Ignore certain combinations
    ignore:
      - goos: windows
        goarch: arm64
    
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Commit={{.Commit}}
      - -X main.Date={{.Date}}
      - -X main.BuiltBy=goreleaser

  - id: ragcode-installer
    main: ./cmd/install
    binary: ragcode-installer
    
    env:
      - CGO_ENABLED=0
    
    goos:
      - linux
      - darwin
      - windows
    
    goarch:
      - amd64
      - arm64
    
    ignore:
      - goos: windows
        goarch: arm64
    
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Commit={{.Commit}}
      - -X main.Date={{.Date}}
      - -X main.BuiltBy=goreleaser

archives:
  - id: default
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    
    # Use zip for Windows
    format_overrides:
      - goos: windows
        format: zip
    
    files:
      - LICENSE
      - README.md
      - config.yaml
      - .env.example

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch
  groups:
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug Fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: 'Performance Improvements'
      regexp: "^.*perf[(\\w)]*:+.*$"
      order: 2
    - title: 'Other Changes'
      order: 999

release:
  github:
    owner: doITmagic
    name: rag-code-mcp
  
  draft: false
  prerelease: auto
  
  name_template: "{{.ProjectName}} v{{.Version}}"
  
  header: |
    ## RagCode MCP Server v{{.Version}}
    
    Semantic code navigation for Go codebases using RAG (Retrieval-Augmented Generation).
    
    ### Installation
    
    **Quick install (Linux/macOS):**
    ```bash
    curl -fsSL https://raw.githubusercontent.com/doITmagic/rag-code-mcp/main/install.sh | bash
    ```
    
    **Or download the binary for your platform below.**
  
  footer: |
    ### What's Next?
    
    1. Install dependencies: Ollama and Qdrant
    2. Configure your environment (see README.md)
    3. Start the server: `rag-code-mcp`
    
    **Full documentation:** https://github.com/doITmagic/rag-code-mcp

# Homebrew tap (optional, can be enabled later)
# brews:
#   - repository:
#       owner: doITmagic
#       name: homebrew-tap
#     homepage: https://github.com/doITmagic/rag-code-mcp
#     description: Semantic code navigation for Go codebases using RAG
#     license: MIT
