package ragcodemcp



















































}	fmt.Println(result)	}		os.Exit(1)		fmt.Fprintf(os.Stderr, "Error: %v\n", err)	if err != nil {	})		"file_path": cwd,	result, err := tool.Execute(ctx, map[string]interface{}{	ctx := context.Background()	tool := tools.NewEvaluateRagCodeTool(wm)	wm := workspace.NewManager(qdrantClient, ollamaProvider, cfg)	defer qdrantClient.Close()	qdrantClient, _ := storage.NewQdrantClient(qcfg)	}		APIKey: cfg.Storage.VectorDB.APIKey,		URL:    cfg.Storage.VectorDB.URL,	qcfg := storage.QdrantConfig{	ollamaProvider, _ := llm.NewOllamaLLMProvider(llmCfg)	llmCfg.Provider = "ollama"	}		llmCfg.OllamaBaseURL = "http://localhost:11434"	if llmCfg.OllamaBaseURL == "" {	llmCfg := cfg.LLM	}		cfg = config.DefaultConfig()	if err != nil {	cfg, err := config.Load(cfgPath)	cfgPath := filepath.Join(cwd, "config.yaml")	cwd, _ := os.Getwd()func main() {)	"github.com/doITmagic/rag-code-mcp/internal/workspace"	"github.com/doITmagic/rag-code-mcp/internal/tools"	"github.com/doITmagic/rag-code-mcp/internal/storage"	"github.com/doITmagic/rag-code-mcp/internal/llm"	"github.com/doITmagic/rag-code-mcp/internal/config"	"path/filepath"	"os"	"fmt"	"context"import (package main