// Package iderules writes RagCode usage rules into the per-IDE locations each
// agent actually reads, so an agent working in an indexed workspace knows the
// tools exist.
//
// Every target here is the current convention for its tool. The flat
// dot-files RagCode used to write (.cursorrules, .windsurfrules, .clauderules)
// are legacy or, in the case of .clauderules, were never a convention at all.
package iderules

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/doITmagic/rag-code-mcp/internal/generatedfile"
	"github.com/doITmagic/rag-code-mcp/internal/logger"
)

// body is the shared rule text. Tool names must match the registered MCP tools.
const body = `# RagCode MCP

This workspace is indexed by RagCode MCP. For anything about the code in it —
where something lives, what it does, who calls it — query the index instead of
guessing or grepping blindly.

- ` + "`rag_search`" + ` — semantic + exact search. Start here.
- ` + "`rag_read_file_context`" + ` — read a file with its symbols and relations.
- ` + "`rag_find_usages`" + ` — every reference to a symbol.
- ` + "`rag_call_hierarchy`" + ` — callers and callees of a function.
- ` + "`rag_list_package_exports`" + ` — the public surface of a package.
- ` + "`rag_index_workspace`" + ` — (re)index when a search comes back empty.

Pass the absolute ` + "`file_path`" + ` of the file you are working on so the
right workspace is resolved.
`

// target is one file to write, with an optional tool-specific front matter.
type target struct {
	path        string
	frontMatter string
}

var targets = []target{
	// Cursor: .cursorrules is deprecated in favour of per-rule .mdc files.
	{filepath.Join(".cursor", "rules", "ragcode.mdc"), "---\ndescription: RagCode MCP semantic code search\nalwaysApply: true\n---\n\n"},
	// Windsurf: .windsurfrules is legacy; rules live in .windsurf/rules/.
	{filepath.Join(".windsurf", "rules", "ragcode.md"), "---\ntrigger: always_on\n---\n\n"},
	// Cline reads .clinerules as either a file or a directory of rules.
	{filepath.Join(".clinerules", "ragcode.md"), ""},
	// Roo Code: .roomodes is mode config, not rules; rules go in .roo/rules/.
	{filepath.Join(".roo", "rules", "ragcode.md"), ""},
}

// claudeFile is written only when absent: CLAUDE.md belongs to the user, and
// clobbering it would throw away their own instructions.
const claudeFile = "CLAUDE.md"

func generated(frontMatter string) string {
	plain := frontMatter + body
	return frontMatter + generatedfile.Marker(plain) + body
}

// Write creates and updates generated rule files, preserving user edits.
func Write(root string) {
	for _, t := range targets {
		path := filepath.Join(root, t.path)
		legacy, desired := t.frontMatter+body, generated(t.frontMatter)
		data, err := os.ReadFile(path)
		if os.IsNotExist(err) || err == nil && (string(data) == legacy || generatedfile.Valid(string(data))) {
			write(path, desired)
		}
	}

	claude := filepath.Join(root, claudeFile)
	data, err := os.ReadFile(claude)
	if os.IsNotExist(err) || err == nil && (string(data) == body || generatedfile.Valid(string(data))) {
		write(claude, generated(""))
	}
	updateLocalExcludes(root, true)
}

// IsGenerated matches unchanged current, legacy, and older generated rules.
func IsGenerated(path string) bool {
	var legacy string
	if filepath.Base(path) == claudeFile {
		legacy = body
	}
	for _, t := range targets {
		if strings.HasSuffix(filepath.ToSlash(path), "/"+filepath.ToSlash(t.path)) {
			legacy = t.frontMatter + body
		}
	}
	if legacy == "" {
		return false
	}
	data, err := os.ReadFile(path)
	return err == nil && (string(data) == legacy || generatedfile.Valid(string(data)))
}

func updateLocalExcludes(root string, install bool) {
	out, err := exec.Command("git", "-C", root, "rev-parse", "--git-path", "info/exclude").Output()
	if err != nil {
		return
	}
	path := strings.TrimSpace(string(out))
	if !filepath.IsAbs(path) {
		path = filepath.Join(root, path)
	}
	data, err := os.ReadFile(path)
	if err != nil && !os.IsNotExist(err) {
		return
	}
	const start = "# BEGIN RagCode generated files\n"
	const end = "# END RagCode generated files\n"
	text := strings.ReplaceAll(string(data), "\r\n", "\n")
	if i := strings.Index(text, start); i >= 0 {
		if j := strings.Index(text[i:], end); j >= 0 {
			text = text[:i] + text[i+j+len(end):]
		}
	}
	if install {
		if text != "" && !strings.HasSuffix(text, "\n") {
			text += "\n"
		}
		text += start + "/.ragcode/\n"
		for _, t := range targets {
			if IsGenerated(filepath.Join(root, t.path)) {
				text += "/" + filepath.ToSlash(t.path) + "\n"
			}
		}
		if IsGenerated(filepath.Join(root, claudeFile)) {
			text += "/" + claudeFile + "\n"
		}
		text += end
	}
	if text != string(data) {
		write(path, text)
	}
}

// Remove deletes only unmodified files generated by Write. Other rules and
// user-edited copies are preserved.
func Remove(root string) {
	updateLocalExcludes(root, false)
	for _, t := range targets {
		path := filepath.Join(root, t.path)
		if !IsGenerated(path) {
			continue
		}
		if err := os.Remove(path); err != nil {
			logger.Instance.Warn("[IDE-RULES] cannot remove %s: %v", path, err)
			continue
		}
		removeEmptyParents(filepath.Dir(path), root)
	}

	claude := filepath.Join(root, claudeFile)
	if IsGenerated(claude) {
		_ = os.Remove(claude)
	}
}

func removeEmptyParents(dir, root string) {
	root = filepath.Clean(root)
	for dir = filepath.Clean(dir); dir != root && strings.HasPrefix(dir+string(os.PathSeparator), root+string(os.PathSeparator)); dir = filepath.Dir(dir) {
		if err := os.Remove(dir); err != nil {
			return
		}
	}
}

func write(path, content string) {
	if existing, err := os.ReadFile(path); err == nil && string(existing) == content {
		return
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		logger.Instance.Warn("[IDE-RULES] cannot create %s: %v", filepath.Dir(path), err)
		return
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		logger.Instance.Warn("[IDE-RULES] cannot write %s: %v", path, err)
		return
	}
	logger.Instance.Debug("[IDE-RULES] wrote %s", path)
}

// Legacy lists the flat rule files earlier RagCode versions dropped in the
// workspace root. They are removed so an agent does not follow stale rules
// naming tools that no longer exist.
var Legacy = []string{".cursorrules", ".windsurfrules", ".clinerules", ".clauderules", ".roomodes"}

// RemoveLegacy deletes the legacy rule files, but only the ones RagCode wrote:
// .clinerules and .roomodes are also valid hand-written config, so a file
// without the RagCode marker is left alone.
func RemoveLegacy(root string) {
	for _, name := range Legacy {
		path := filepath.Join(root, name)
		data, err := os.ReadFile(path)
		if err != nil || !strings.Contains(string(data), "RagCode MCP") {
			continue
		}
		if err := os.Remove(path); err != nil {
			logger.Instance.Warn("[IDE-RULES] cannot remove legacy %s: %v", path, err)
			continue
		}
		logger.Instance.Info("[IDE-RULES] removed legacy rule file %s", path)
	}
}
